### ISSUE TITLE
using groups and ESSV3

### ISSUE THREAD

**Issue by SmokeyBR** [ebayShopper/ESSV3#13]
Not sure you can call this an issue, more of a heads up.
but after testing a problem on my server with player not being added automatically after dying i found that groups wont update if a player looses and regain radio while inside a group (have to either relog or get invited again)

while you are picking classes radio is not added for the player and so it wont rejoin group once u pick a class with radio unless you relog

**Comment by SmokeyBR** [comment]
to fix my problem i had to add `DefaultWeapons = ["ItemRadio"];` to my init

**Comment by ebayShopper** [comment]
https://github.com/EpochModTeam/DayZ-Epoch/commit/75a12ad9532231b5db547f7f71bf69a5c8187008

0125715
