### ISSUE TITLE
installed enhanced spawn

### ISSUE THREAD

**Issue by jdcarl123** [ebayShopper/ESSV3#17]
I set it up like your instruction stated. But upon trying to spawn in with it there are no classes in the clase selection screen

**Comment by T-E-X** [comment]
that happened to me once too, I started over and read the directions slower and it worked the second time.

**Comment by jdcarl123** [comment]
Idk if this could be the issue but i cant find the battleeye filters to add them but it doest seem to have affect my infistar install
