### ISSUE TITLE
Show VIP/Custom load outs first in spawn menu

### ISSUE THREAD

**Issue by oiad** [ebayShopper/ESSV3#2]
Hey,

Would it be a good idea to list the VIP/Custom load outs before the default load outs? Since most players will select their own loadout, I changed the order on my version of these two lines:

https://github.com/ebayShopper/ESSV3/blob/master/spawn/main.sqf#L37

`class_public = (spawn_config select 0) + class_public;`
`spawn_public = (spawn_config select 1) + spawn_public;`

Or maybe a variable to select one or the other direction

**Comment by ebayShopper** [comment]
Sure, or just add an lbSort and then use some prefix in your class names like * or whatever.
