### ISSUE TITLE
how to set player position in map 1.0.6.1 

### ISSUE THREAD

**Issue by Bossku-JK** [ebayShopper/ESSV3#5]
Help me pls  
add it to ?

_unit = _this select 0;
_markername = "yourPosition";
_getPos = getPos _unit;
_position = [_getPos select 0, _getPos select 1];
 
deleteMarker _markername;
 
_marker  = createMarkerLocal [_markername,_position];
_marker setMarkerTypeLocal "DestroyedVehicle";
_marker setMarkerTextLocal "You are here.";
systemchat "Your Position marked on the map";
sleep 60;

deleteMarker _markername;

**Comment by ebayShopper** [comment]
This feature is built into Epoch 1.0.6+ group system. Just copy paste this line into your mission init.sqf below the #include line:
https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/configVariables.sqf#L106
