### ISSUE TITLE
class_preview

### ISSUE THREAD

**Issue by DokerRS** [ebayShopper/ESSV3#9]
Error in expression < in weapons class_bot) then {
class_bot addWeapon _x;
};
} count _weps;

if (pri>
  Error position: <addWeapon _x;
};
} count _weps;

if (pri>
  Error Generic error in expression
File mpmissions\__CUR_MP.Chernarus\spawn\functions\class_preview.sqf, line 32

**Comment by ebayShopper** [comment]
It looks like you have a magazine in one of your weapons arrays, but I can't tell for sure without seeing your two config files. Make sure your classes are in the right format:
https://github.com/ebayShopper/ESSV3/blob/master/DOCUMENTATION.md
